# Generated by Django 4.2.4 on 2023-10-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
